[CORE-11989] Update cherry-pick scripts (#10017)
* Replace `hub` to `gh`

* optionally use PR diff instead of format-patch

* Replace `hub` to `gh` in pick-oss-pr script

* Fix `gh pr create`

* Fix typo

diff --git a/hack/cherry-pick-pull b/hack/cherry-pick-pull
--- a/hack/cherry-pick-pull
+++ b/hack/cherry-pick-pull
@@ -27,6 +27,7 @@ set -o nounset
 set -o pipefail
 
 function init-vars() {
+  THIS_SCRIPT=$(basename "$0")
   REPO_ROOT="$(git rev-parse --show-toplevel)"
   declare -rg REPO_ROOT
   cd "${REPO_ROOT}"
@@ -51,14 +52,15 @@ function init-vars() {
     echo "Can't parse $DST_UPSTREAM_REMOTE URL to set DST_MAIN_REPO_ORG or DST_MAIN_REPO_NAME."
     exit 1
   fi
-  
+  SQUASH_COMMITS=${SQUASH_COMMITS:-""}
+
   if [[ -z ${GITHUB_USER:-} ]]; then
     echo "Please export GITHUB_USER=<your-user> (or GH organization, if that's where your fork lives)"
     exit 1
   fi
   
-  if ! which hub > /dev/null; then
-    echo "Can't find 'hub' tool in PATH, please install from https://github.com/github/hub"
+  if ! which gh > /dev/null; then
+    echo "Can't find 'gh' tool in PATH, please install: https://cli.github.com/"
     exit 1
   fi
   
@@ -67,9 +69,9 @@ function init-vars() {
     echo
     echo "  Checks out <remote branch> and handles the cherry-pick of <pr> (possibly multiple) for you."
     echo "  Examples:"
-    echo "    $(basename $0) upstream/release-3.14 12345        # Cherry-picks PR 12345 onto upstream/release-3.14 and proposes that as a PR."
-    echo "    $(basename $0) upstream/release-3.14 12345 56789  # Cherry-picks PR 12345, then 56789 and proposes the combination as a single PR."
-    echo "    SRC_UPSTREAM_REMOTE=open-source DST_UPSTREAM_REMOTE=upstream $(basename $0) upstream/release-3.14 12345"
+    echo "    ${THIS_SCRIPT} upstream/release-3.14 12345        # Cherry-picks PR 12345 onto upstream/release-3.14 and proposes that as a PR."
+    echo "    ${THIS_SCRIPT} upstream/release-3.14 12345 56789  # Cherry-picks PR 12345, then 56789 and proposes the combination as a single PR."
+    echo "    SRC_UPSTREAM_REMOTE=open-source DST_UPSTREAM_REMOTE=upstream ${THIS_SCRIPT} upstream/release-3.14 12345"
     echo "    # ^- Cherry-picks PR 12345 from the 'open-source' remote to the 'upstream' remote, to the upstream/release-3.14 base branch and proposes that as a PR."
     echo
     echo "  Set the DRY_RUN environment var to skip git push and creating PR."
@@ -85,6 +87,9 @@ function init-vars() {
     echo " Use a different SRC_UPSTREAM_REMOTE and DST_UPSTREAM_REMOTE if you would like to cherry-pick a pull request"
     echo " across different repos. For example, to cherry-pick a pull request from the repo defined as the 'open-source'"
     echo " remote into the repo defined as 'upstream', use SRC_UPSTREAM_REMOTE=open-source DST_UPSTREAM_REMOTE=upstream."
+    echo
+    echo " Use SQUASH_COMMITS=1 if you want to have all original PR diffs consolidated into a single patch and applied with 'git apply',"
+    echo " otherwise all original commits in 'git format-patch' style will be applied with 'git am'"    
     exit 2
   fi
   
@@ -173,7 +178,7 @@ function make-a-pr() {
     new_header+="- Pick onto **$rel**:"$'\n'
   fi
   for pullnumber in "${PULLS[@]}"; do
-    local pull_json=$(hub api repos/${SRC_MAIN_REPO_ORG}/${SRC_MAIN_REPO_NAME}/pulls/${pullnumber})
+    local pull_json=$(gh pr view -R "${SRC_MAIN_REPO_ORG}/${SRC_MAIN_REPO_NAME}" "${pullnumber}" --json title,body,labels)
     local pull_title=$(echo "${pull_json}" | jq -r '.title')
     local pull_body=$(echo "${pull_json}" | jq -r '.body')
     local pull_labels=$(echo "${pull_json}" | jq -r '.labels[].name' | paste -sd$'\n')
@@ -228,10 +233,6 @@ function make-a-pr() {
     fi
   fi
 
-  # This looks like an unnecessary use of a tmpfile, but it avoids
-  # https://github.com/github/hub/issues/976 Otherwise stdin is stolen
-  # when we shove the heredoc at hub directly, tickling the ioctl
-  # crash.
   pr_body_file="$(mktemp -t prtext.XXXX)" # cleaned in return_to_kansas
   
   cat >"${pr_body_file}" <<EOF
@@ -245,10 +246,16 @@ EOF
     echo
     cat "${pr_body_file}"
   else 
-    hub pull-request \
+    if gh repo set-default --view 2>&1 | grep -q "No default remote"; then
+      echo "+++ Default repo must be set. Running: gh repo set-default"
+      gh repo set-default
+    fi
+    echo "+++ Creating PR. Running: gh pr create -t \"[${relshort}] ${new_title}\" -F \"${pr_body_file}\" -H \"${GITHUB_USER}:${NEWBRANCH}\" -B \"${DST_MAIN_REPO_ORG}:${rel}\" -l \"${new_labels}\""
+    gh pr create \
+      -t "[${relshort}] ${new_title}" \
       -F "${pr_body_file}" \
-      -h "${GITHUB_USER}:${NEWBRANCH}" \
-      -b "${DST_MAIN_REPO_ORG}:${rel}" \
+      -H "${GITHUB_USER}:${NEWBRANCH}" \
+      -B "${rel}" \
       -l "${new_labels}"
   fi
 }
@@ -261,13 +268,29 @@ function create-branch-and-pr() {
   gitamcleanup=true
   for pull in "${PULLS[@]}"; do
     echo "+++ Downloading patch to /tmp/${pull}.patch (in case you need to do this again)"
-  
-    hub api -X GET -H "Accept: application/vnd.github.v3.patch;charset=utf-8" repos/${SRC_MAIN_REPO_ORG}/${SRC_MAIN_REPO_NAME}/pulls/${pull} > "/tmp/${pull}.patch"
+    if [[ -n "${SQUASH_COMMITS}" ]]; then
+      gh pr diff --repo ${SRC_MAIN_REPO_ORG}/${SRC_MAIN_REPO_NAME} ${pull} > /tmp/${pull}.patch
+    else
+      gh api -H "Accept: application/vnd.github.v3.patch" /repos/${SRC_MAIN_REPO_ORG}/${SRC_MAIN_REPO_NAME}/pulls/${pull} > /tmp/${pull}.patch
+    fi
+
+    apply_cmd="git am --empty=keep -3 \"/tmp/${pull}.patch\""
+    add_cmd="git add / git am --continue"
+    if [[ -n "${SQUASH_COMMITS}" ]]; then
+      apply_cmd="git apply -p1 -3 \"/tmp/${pull}.patch\""
+      add_cmd="git add"
+    fi
+
     echo
     echo "+++ About to attempt cherry pick of PR. To reattempt:"
-    echo "  $ git am -3 /tmp/${pull}.patch"
+    echo "  $ ${apply_cmd}"
     echo
-    git am -3 "/tmp/${pull}.patch" || {
+
+    if (eval "${apply_cmd}"); then
+      # If patch is applied cleanly, add files, they will be committed later
+      git add .
+    else
+      # If there are conflicts, prompt user to resolve them in another window and continue
       conflicts=false
       while unmerged=$(git status --porcelain | grep ^U) && [[ -n ${unmerged} ]] \
         || [[ -e "${REBASEMAGIC}" ]]; do
@@ -275,9 +298,9 @@ function create-branch-and-pr() {
         echo
         echo "+++ Conflicts detected:"
         echo
-        (git status --porcelain | grep ^U) || echo "!!! None. Did you git am --continue?"
+        (git status --porcelain | grep ^U) || echo "!!! None. Did you '${add_cmd}'?"
         echo
-        echo "+++ Please resolve the conflicts in another window (and remember to 'git add / git am --continue')"
+        echo "+++ Please resolve the conflicts in another window (and remember to '${add_cmd}')"
         read -p "+++ Proceed (anything but 'y' aborts the cherry-pick)? [y/n] " -r
         echo
         if ! [[ "${REPLY}" =~ ^[yY]$ ]]; then
@@ -287,11 +310,17 @@ function create-branch-and-pr() {
       done
   
       if [[ "${conflicts}" != "true" ]]; then
-        echo "!!! git am failed, likely because of an in-progress 'git am' or 'git rebase'"
+        echo "!!! git am / git apply failed, likely because of an in-progress 'git am' or 'git rebase'"
         exit 1
       fi
-    }
+    fi
   
+    # When squashing, commit patch changes with the same message as the merge commit from the original PR
+    if [[ -n "${SQUASH_COMMITS}" ]]; then
+      merge_commit_hash=$(gh pr view --repo "${SRC_MAIN_REPO_ORG}/${SRC_MAIN_REPO_NAME}" ${pull}  --json mergeCommit -q .mergeCommit.oid)
+      git commit -C ${merge_commit_hash}
+    fi
+
     # remove the patch file from /tmp
     rm -f "/tmp/${pull}.patch"
   done
@@ -323,7 +352,7 @@ function create-branch-and-pr() {
     exit 0
   fi
   
-  if git remote -v | grep ^${FORK_REMOTE} | grep \<${DST_MAIN_REPO_ORG}/${DST_MAIN_REPO_NAME}.git; then
+  if git remote -v | grep ^"${FORK_REMOTE}" | grep \<"${DST_MAIN_REPO_ORG}"/"${DST_MAIN_REPO_NAME}".git; then
     echo "!!! You have ${FORK_REMOTE} configured as your ${DST_MAIN_REPO_ORG}/${DST_MAIN_REPO_NAME}.git"
     echo "This isn't normal. Leaving you with push instructions:"
     echo
